android_resource(
  name = 'res',
  res = 'res',
  assets = 'assets',  
  package = 'io.selendroid.server',
  visibility = [ 'PUBLIC' ],
)
project_config(
  src_target = ':res',
  src_roots = [ 'res','assets'],
)
