python_library(
  name = 'util',
  srcs = [
    'util.py',
  ],
  visibility = ['PUBLIC'],
)

python_test(
  name = 'util_test',
  srcs = ['util_test.py'],
  deps = [':util'],
  visibility = ['PUBLIC'],
)